apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: k8s-cluster
spec:
  repo: https://kubernetes.github.io/ingress-nginx
  chart: ingress-nginx
  version: 4.13.2
  targetNamespace: kube-system
  createNamespace: false
  failurePolicy: abort
  values:
    controller:
      replicaCount: 1
      service:
        type: ClusterIP
      hostNetwork: false
      hostPort:
        enabled: true
        ports:
          http: 80
          https: 443
      config:
        proxy-body-size: 100m
      watchIngressWithoutClass: true
      ingressClassResource:
        name: nginx
        enabled: true
        default: true
      extraArgs:
        default-ssl-certificate: kube-system/wildcard-ncrmro-com-tls
